permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 柯均洁
  email: kjj3300@163.com
  link: http://junjiek.com
  github: http://github.com/junjiek

# 站点信息
title: 柯均洁的博客 
description: 柯均洁的博客
url: http://junjiek.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://7u2ho6.com1.z0.glb.clouddn.com/site-avatar.png
favicon: http://7u2ho6.com1.z0.glb.clouddn.com/site-favicon.ico

# google analytics 设置
ga:
  id: UA-54767140-1
  url: junjiek.com

# disqus 设置
disqus:
  shortname: suyan-zh