permalink: /:year/:month/:day/:title.html
markdown: kramdown
pygments: true

kramdown:
  input: GFM

# 作者信息
author: 
  name: 柯均洁
  email: kjj3300@163.com
  link: http://junjiek.com
  github: http://github.com/junjiek

# 站点信息
title: 柯均洁的博客 
description: 柯均洁的博客
url: http://junjiek.com
rss_url: /pages/atom.xml

# avatar头像及Favicon
avatar: http://ww1.sinaimg.cn/thumb180/6a5b2847jw1dstk863du5j.jpg
favicon: http://img6.douban.com/view/photo/photo/public/p2254493685.jpg

# google analytics 设置
ga:
  id: UA-64827079-1
  url: junjiek.com

# disqus 设置
disqus:
  shortname: junjiekcom